services:

  db:
    image: docker.io/pgvector/pgvector:pg17@sha256:40b404964359299eefdd5f8518facf1886c562848cf4de13b6eaf91cb70c2b87
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secrete
      POSTGRES_DB: ragdb
    ports:
      - 5432:5432
    volumes:
      - blograg_pgdata:/var/lib/postgresql/data

  adminer:
    image: docker.io/library/adminer:latest@sha256:f6cd54b6269f33f55d9a1cc1e7e76e67f42d2fad5e95fae641f4dcc1705729a1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  blograg_pgdata:
