services:

  db:
    image: docker.io/pgvector/pgvector:pg17@sha256:0300b0eb0e177439e5fc415a481f72f1ba5d7cd3852101e200b95e86a440240b
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secrete
      POSTGRES_DB: ragdb
    ports:
      - 5432:5432
    volumes:
      - blograg_pgdata:/var/lib/postgresql/data

  adminer:
    image: docker.io/library/adminer:latest@sha256:f6cd54b6269f33f55d9a1cc1e7e76e67f42d2fad5e95fae641f4dcc1705729a1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  blograg_pgdata:
